import './globals.css'
import {FC, PropsWithChildren} from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<PropsWithChildren> = ({children}) => {
    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    )
}
export default RootLayout;
