import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import useTranslation from "next-translate/useTranslation";


export default function Home() {
    const {t, lang} = useTranslation('Home');
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.links}>
                    <Link href={'/'} locale={'en'}>
                        En
                    </Link>
                    <Link href={'/'} locale={'ru'}>
                        RU
                    </Link></div>
                <h1>
                    {t('title')}
                </h1>
            </main>
        </>
    )
}