import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";
import { LanguageSelect } from "@/components/LanguageSelect/LanguageSelect";

export default function Home() {
  const { t, lang } = useTranslation("Home");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LanguageSelect />
        <h1>{t("title")}</h1>
      </main>
    </>
  );
}
